mytest2: 777

spring:
  profiles:
    active: dev

# 字符串
myString1: 你好，\n世界
myString2: '你好，\n世界'
myString3: "你好，\\n世界"

# 自定义对象
#student:
#  id: 1
#  name: alice
#  age: 18

student: {id: 2, name: mary, age: 19}
